
create table roles (
    id integer generated by default as identity,
    name varchar(30) not null UNIQUE,
    primary key (id)
);

create table users (
    id bigint generated by default as identity,
    email varchar(30) not null UNIQUE,
    password varchar(255) not null,
    username varchar(30) not null UNIQUE,
    primary key (id)
);

create table user_roles (
    user_id bigint not null,
    role_id integer not null
);
