

create table tasks (
    id bigint generated by default as identity,
    description varchar(255) not null,
    priority varchar(255) not null check (priority in ('LOW','MEDIUM','HIGH')),
    status varchar(255) not null check (status in ('PENDING','IN_PROGRESS','COMPLETED')),
    title varchar(255) not null,
    author_id bigint,
    executor_id bigint,
    primary key (id)
);


create table comments (
    id bigint generated by default as identity,
    date date not null,
    text varchar(255) not null,
    author_id bigint,
    primary key (id)
);

create table tasks_comments (
    task_entity_id bigint not null,
    comments_id bigint not null
);

